services:
  - type: web
    name: n8n
    env: docker
    plan: free
    branch: master
    dockerfilePath: ./Dockerfile
    envVars:
      - key: GENERIC_TIMEZONE
        value: Asia/Kolkata
      - key: N8N_BASIC_AUTH_USER
        value: prasanna
      - key: N8N_BASIC_AUTH_PASSWORD
        value: StrongPassword123!
